### PR TITLE
Fix including with blank relationships

### PR DESCRIPTION
**Pull request by stokarenko**
It fixes the minor breaking change introduced by https://github.com/JsonApiClient/json_api_client/commit/3048ea371e8fc5e5f5b6788c870503c09d2391f4#diff-cd00f457f4dd1dac9e58ef9c63390ca1R514:

**Given**: user = DocumentUser.includes('file').find(1).first
**When**: resource is coming with blank `relationships['file']` json-api data
**Expected**: user.file to be nil
**Actual**: the exception raised

> NoMethodError: undefined method `[]' for nil:NilClass
    json_api_client/lib/json_api_client/resource.rb:549:in `relationship_data_for'

### CODE REVIEW

**Comment by stokarenko** [comment]
@gaorlov Hi again )

**Comment by gaorlov** [comment]
hahaha! perfect. Can you update the change log and i'll push out `1.12.2`.

Thanks!

**Comment by stokarenko** [comment]
done! )

**Comment by stokarenko** [comment]
I see,  fixing, 10 mins )

**Comment by gaorlov** [comment]
@stokarenko `1.12.2` is live. Thanks once again!

**Comment by gaorlov** [comment]
`1.14.0` is live. Thanks for the contribution!
