### PR TITLE
Fix resource including for STI objects

### PR DESCRIPTION
**Pull request by stokarenko**
The problem was introduced by https://github.com/JsonApiClient/json_api_client/pull/305

When we including the kind of STI resource, we are running in issue with unexpected `type` attribute:

**Given**: resource is kind of 'file' type, with 'type' attribute equals to `STIDocumentFile`
**When**: we including such resource
**Expected**: `parent_resource.file` to be available as usually
**Actual**: the exception raised
```
NoMethodError:
       undefined method `[]' for nil:NilClass
     # /gems/json_api_client-1.12.0/lib/json_api_client/included_data.rb:46:in `record_for'
```

This happens because of

```ruby
module JsonApiClient
  class IncludedData
    def initialize(result_set, data)
       # ...
       # `parameters_from_resource` will override the actual resource `type` value
       # with value from attribute `type`
       params = klass.parser.parameters_from_resource(datum)
       # ...
       # such overridden `type` is used for grouping.
       # i.e. the resources will be grouped by `STIDocumentFile` instead of `file`
       @data = included_set.group_by(&:type)
       # ...
    end
  end
end
```

### CODE REVIEW

**Comment by stokarenko** [comment]
@gaorlov FYI )

**Comment by stokarenko** [comment]
Will fix the missing `transform_values` method on Monday )

File: lib/json_api_client/included_data.rb [hunk 1]
```diff
@@ -4,20 +4,30 @@ class IncludedData
 
     def initialize(result_set, data)
       record_class = result_set.record_class
-      included_set = data.map do |datum|
-        type = datum["type"]
+      grouped_data = data.group_by{|datum| datum["type"]}
+      included_set = grouped_data.each_with_object({}) do |(type, records), h|
```
Comment (gaorlov) [inline lib/json_api_client/included_data.rb]: How would you feel about renaming this to `grouped_included_set` for clarity?

File: lib/json_api_client/included_data.rb [hunk 2]
```diff
@@ -4,20 +4,30 @@ class IncludedData
...
         klass = Utils.compute_type(record_class, record_class.key_formatter.unformat(type).singularize.classify)
-        params = klass.parser.parameters_from_resource(datum)
-        resource = klass.load(params)
-        resource.last_result_set = result_set
-        resource
+        h[type] = records.map do |datum|
```
Comment (gaorlov) [inline lib/json_api_client/included_data.rb]: For the sake of consistency, can we rename `datum` to `record`?

**Comment by stokarenko** [comment]
@gaorlov Applied all the things, also added the record to changelog )

Thank you a lot for assistance! )

**Comment by gaorlov** [comment]
Marvelous. Thanks once again!

**Comment by gaorlov** [comment]
@stokarenko `1.12.1` is now live.
